### ISSUE TITLE
`svelte-time` version 0.7.1 doesn't work with Snowpack

### ISSUE THREAD

**Issue by metonym** [metonym/svelte-time#23]
I'm recording this as a known issue. Version 0.7.1 switched back to using CJS instead of ESM imports from `dayjs` in order to unblock usage with SvelteKit.

Running `snowpack` in development works fine; however, building the app for production will throw the following error:

```sh
Duplicate export 'default... in node_modules/dayjs/dayjs.min.js
```

The workaround is to either pin the `svelte-time` version to v0.7.0 or copy the [source code](https://github.com/metonym/svelte-time/tree/master/src) and update [src/dayjs.js](https://github.com/metonym/svelte-time/blob/master/src/dayjs.js) to the following:

```diff
- import dayjs from "dayjs";
- import relativeTime from "dayjs/plugin/relativeTime.js";
+ import dayjs from "dayjs/esm";
+ import relativeTime from "dayjs/esmplugin/relativeTime";
```

**Comment by KieranP** [comment]
With vite/svelte and latest versions of svelte-time/dayjs, I get the following error:

```
Uncaught SyntaxError: The requested module '/vite-dev/@fs/Volumes/Work/node_modules/dayjs/plugin/relativeTime.js?v=1f51ad4b' does not provide an export named 'default' (at dayjs.js:2:8)
```

**Comment by Van-Dame** [comment]
Same issue as @KieranP. Rolling back to 0.7.0 fixes the issue. 

    ❯ npm init vite@latest vite-svelte-repro -- --template svelte-ts
    ❯ npm i svelte-time@0.7.1

    import Time from 'svelte-time';

    ❯ npm run dev


**Browser:** 
`Uncaught SyntaxError: The requested module 'relativeTime.js?v=1f51ad4b' does not provide an export named 'default' (at dayjs.js:2:8)`

**Comment by KieranP** [comment]
@metonym I do not have dayjs as a direct dependency.

@Van-Dame Thank you for the tip. Going back to 0.7.0 does indeed resolve the issue.

**Comment by metonym** [comment]
@Van-Dame Thank you for the vite repro. I see the error in `dev` but not when building it.

Could you specify `"dayjs/plugin/relativeTime.js"` in the `vite.optimizeDeps.include`?

```js
// vite.config.js
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { defineConfig } from "vite";

export default defineConfig(() => {
  return {
    plugins: [svelte()],
    optimizeDeps: {
      include: ["dayjs/plugin/relativeTime.js"],
    },
  };
});

```

I'm still unable to repro the bug while using SvelteKit (1.0.0-next.357) with the Node adapter.

**Comment by Van-Dame** [comment]
@metonym Updated to v0.7.1 and added your workaround., Can confirm it works! 👍🏻
